name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:      # Manual trigger allowed

permissions:
  security-events: write  # Required to upload SARIF reports

jobs:
  DependenciesAnalysis:
    name: Dependency and Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        run: |
          curl -LO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64
          chmod +x osv-scanner-linux-amd64
          mv osv-scanner-linux-amd64 osv-scanner
          ./osv-scanner --format sarif --output osv.sarif --recursive .

      - name: Upload OSV SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv.sarif

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          semgrep --config p/java --sarif --output semgrep.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

