name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 1 * * *'  # Every day at 01:00 UTC
  workflow_dispatch:      # Allows manual execution

permissions:
  contents: read
  security-events: write  # Required to publish SARIF reports

jobs:
  DependenciesAnalysis:
    name: Analyse Semgrep (Java)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep --config=p/java --sarif --output=semgrep-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif

  SourceCodeAnalysis:
    name: Analyse OSV Scanner
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.2

